const respuestas = [
  'Tal vez',
  'No estoy seguro, pregúntame más tarde',
  'Parece poco probable',
  'Las circunstancias indican que sí',
  'Es improbable',
  'No puedo predecirlo en este momento',
  'Es una posibilidad',
  'Requiere más investigación',
  'Depende de varios factores',
  'Podría ser así',
  'No puedo responder con certeza',
  'La respuesta está en tus manos',
  'Es una incógnita',
  'Las señales apuntan a que no',
  'Es una posibilidad remota',
  'No estoy convencido/a',
  'Es poco probable en estas circunstancias',
  'No puedo descartarlo por completo',
  'Es cuestionable',
  'No puedo proporcionar una respuesta definitiva',
  'Todo indica que sí',
  'No confiaría en ello',
  'Es difícil de predecir',
  'No puedo ofrecerte una respuesta clara',
  'Es poco probable, pero no imposible',
  'Depende de la suerte que tengas',
  'Si',
  'No',
  'Posiblemente',
  'Seguro que no',
  'Obviamente',
  'Es cierto',
  'Definitivamente',
  'Lo mas probable',
  'No tengo una respuesta para eso..',
  'No podria confirmartelo',
  'No cuentes con ello',
  'Es muy dudoso',
  'Creeria que si',
  'Diria que no',
  'Los astros aun no se alinean',
  'Es posible',
  'No veo eso sucediendo',
  'No puedo afirmar ni negar',
  'Podría ser cierto',
  'No estoy capacitado para responder eso',
  'Las probabilidades son bajas',
  'Todo apunta a que sí',
  'No cuentes con ello',
  'Es demasiado pronto para decirlo',
  'No puedo revelar esa información',
  'No hay manera de saberlo',
  'No tengo suficiente información',
  'Depende de tu perspectiva'
]
const respuestasAdicionales = [
  'Es una posibilidad intrigante',
  'No puedo confirmar ni negar eso',
  'Podría ir en cualquier dirección',
  'No puedo ofrecerte una respuesta definitiva en este momento',
  'Es poco probable, pero no se puede descartar',
  'No tengo suficiente información para responder',
  'Parece poco probable en este momento',
  'No puedo garantizarlo',
  'Es complicado',
  'No puedo dar una respuesta concluyente',
  'Las perspectivas son inciertas',
  'No tengo capacidad para predecir eso',
  'La respuesta está en constante cambio'
]
const respuestasSarcasticas = [
  '¡Claro, y los cerdos vuelan!',
  'Sí, cuando los unicornios dominen el mundo',
  'No, nunca en un millón de años',
  'Oh, seguro, y el sol sale por el oeste',
  'Por supuesto, cuando los pingüinos vuelen',
  'Obviamente, en el país de las maravillas',
  '¡Sí, y yo soy el rey de Marte!',
  'No, eso solo sucede en los cuentos de hadas',
  'Por supuesto, cuando los peces canten ópera',
  'Sí, cuando los elefantes vuelen',
  'No, eso solo ocurre en las películas',
  '¡Claro, cuando los icebergs estén hechos de chocolate!',
  'Sí, cuando los zombies ganen un premio Nobel'
]

const respuestasKawaii = [
  '¡Sí, por supuesto! Es más lindo que un gatito con un sombrero de flores',
  '¡Nya! ¡Definitivamente sí!',
  '¡Claro, es tan kawaii como un unicornio de algodón de azúcar!',
  '¡Seguro que sí! Es tan adorable como un cachorro jugando en un prado de margaritas',
  '¡Síii! Es tan dulce como un pastelito con cara sonriente',
  '¡Kawaii desu! Sin duda alguna',
  '¡Ohayou! ¡Definitivamente es kawaii!',
  '¡Sugoi kawaii! ¡Absolutamente sí!',
  '¡Mochi-mochi! ¡No puedo resistirme a decir que sí!',
  '¡Kawaii neko! ¡Por supuesto!',
  '¡Nyaa~! ¡Es tan kawaii como un conejito saltando sobre nubes de algodón!',
  '¡Nyan nyan! ¡Absolutamente kawaii!',
  '¡Sí, es tan kawaii como un arco iris de chucherías!'
]
const respuestasMeme = [
  'Sí, xd, como si eso fuera a pasar',
  'No, definitivamente no :v',
  'Posiblemente, pero no te hagas ilusiones, jajaja',
  'Seguro que no, xd, ni en tus sueños más locos',
  'Obviamente, ¿qué no ves que soy un genio? :v',
  'Es cierto, xd, pero no se lo cuentes a nadie',
  'Definitivamente, mano :v',
  'Lo más probable, xd, pero no apuestes tu vida en ello',
  'No tengo una respuesta para eso, xd, así que mejor sigue preguntando',
  'No podría confirmártelo, xd, no tengo poderes mágicos',
  'No cuentes con ello, :v, eso sería muy loco',
  'Es muy dudoso, jajaja, mejor busca otra opción',
  'Creería que sí, xd, pero tampoco es para emocionarse tanto',
  'Diría que no, :v, pero siempre hay esperanza'
]

const respuestasCompletas = respuestas.concat(
  respuestasAdicionales,
  respuestasSarcasticas,
  respuestasKawaii,
  respuestasMeme
)

module.exports = [...respuestasCompletas]
